"""The Understanding Report (CLAUDE.md §9.7, U5): a revision sheet with the Ownership Score
breakdown, the understanding checks, concepts mastered and to revise, the glossary, every viva
question with the student's answer and feedback, and a concept list for revision."""

from __future__ import annotations

from datetime import date

from docx.document import Document as DocxDocument
from docx.shared import Pt, RGBColor

from app.export.docx_writer import new_document, to_bytes
from app.schemas.export import UnderstandingReportRequest

MUTED = RGBColor(0x5F, 0x5F, 0x5F)
SOURCE_LABEL = {
    "yours": "your definition",
    "document": "from your text",
    "abbreviation": "abbreviation list",
    "wordnet": "dictionary",
}


FOOTER = "Generated by OwnIt. No AI models were used: every score comes from your work in the app."


def _pct(x: float | None) -> str:
    return "—" if x is None else f"{round(x)}%"


def _table(doc: DocxDocument, header: list[str], rows: list[list[str]]) -> None:
    t = doc.add_table(rows=1, cols=len(header))
    t.style = "Light Grid Accent 1"
    for cell, text in zip(t.rows[0].cells, header, strict=True):
        cell.text = text
        for r in cell.paragraphs[0].runs:
            r.bold = True
    for row in rows:
        cells = t.add_row().cells
        for cell, text in zip(cells, row, strict=True):
            cell.text = text


def _muted(doc: DocxDocument, text: str) -> None:
    run = doc.add_paragraph().add_run(text)
    run.italic = True
    run.font.color.rgb = MUTED
    run.font.size = Pt(9.5)


def _bullets(doc: DocxDocument, items: list[str], empty: str) -> None:
    if not items:
        _muted(doc, empty)
    for item in items:
        doc.add_paragraph(item, style="List Bullet")


def build_report(d: UnderstandingReportRequest) -> bytes:
    doc = new_document(f"Understanding Report: {d.title}", d.author)
    doc.add_heading("Understanding Report", level=0)
    doc.add_paragraph(d.title, style="Subtitle")
    doc.add_paragraph(
        " · ".join(x for x in (d.author, d.date or date.today().strftime("%d %B %Y")) if x)
    )

    # 1. ownership
    doc.add_heading("Ownership", level=1)
    share = round(d.student_share * 100)
    headline = f"Ownership Score {round(d.ownership_score)}/100 · you wrote {share}% of the text"
    doc.add_paragraph().add_run(headline).bold = True
    if d.ownership_parts:
        _table(
            doc,
            ["Part", "Weight", "Result", "Detail"],
            [
                [
                    p.label,
                    f"{p.weight:.2f}",
                    "n/a" if p.value is None else f"{round(p.value * 100)}%",
                    p.detail,
                ]
                for p in d.ownership_parts
            ],
        )

    # 2. understanding checks
    doc.add_heading("Understanding checks", level=1)
    if d.gate:
        _table(
            doc,
            ["Check", "Your result", "Required", "Status"],
            [
                [
                    g.label,
                    _pct(g.value),
                    f"{round(g.required)}%",
                    "passed" if g.passed else "not yet",
                ]
                for g in d.gate
            ],
        )
    doc.add_paragraph("All checks passed." if d.gate_passed else "Not all checks are passed yet.")

    # 3. concepts
    doc.add_heading("Concepts", level=1)
    doc.add_heading("Mastered", level=2)
    _bullets(doc, d.mastered, "None recorded yet.")
    doc.add_heading("To revise", level=2)
    _bullets(doc, d.weak, "Nothing flagged. Well done.")

    # 4. glossary
    doc.add_heading("Glossary", level=1)
    if d.glossary:
        _table(
            doc,
            ["Term", "Definition", "Source"],
            [
                [
                    g.term,
                    g.definition or "(define it in your own words)",
                    SOURCE_LABEL.get(g.source or "", g.source or ""),
                ]
                for g in d.glossary
            ],
        )
    else:
        _muted(doc, "No glossary yet: open the Walkthrough step.")

    # 5. viva practice
    doc.add_heading("Viva practice", level=1)
    if not d.viva:
        _muted(doc, "No viva session yet.")
    for k, v in enumerate(d.viva, 1):
        p = doc.add_paragraph()
        p.add_run(f"Q{k}. {v.question}").bold = True
        if v.difficulty:
            meta = p.add_run(f"  ({v.difficulty} · score {round(v.score)})")
            meta.font.color.rgb = MUTED
        doc.add_paragraph(f"Your answer: {v.answer.strip() or '(no answer)'}")
        if v.feedback:
            _muted(doc, v.feedback)

    # 6. quiz and teach-back
    doc.add_heading("Quiz and teach-back", level=1)
    doc.add_paragraph(f"Quiz score: {_pct(d.quiz_total)}")
    for m in d.quiz_missed:
        doc.add_paragraph(
            f"{m.prompt} → {m.answer_key}"
            + (f" (you wrote: {m.your_answer})" if m.your_answer else ""),
            style="List Bullet",
        )
    doc.add_paragraph(f"Teach-back coverage: {_pct(d.teachback_coverage)}")
    if d.teachback_explanation:
        q = doc.add_paragraph(style="Quote")
        q.add_run(d.teachback_explanation.strip())
    if d.teachback_missed:
        doc.add_paragraph("Not yet explained: " + ", ".join(d.teachback_missed))

    # 7. revision list
    doc.add_heading("Revision list", level=1)
    revision = list(dict.fromkeys([*d.weak, *d.teachback_missed]))
    _bullets(doc, revision, "Nothing to revise.")

    _muted(doc, FOOTER)
    return to_bytes(doc)
