/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze */
        post: operations["analyze_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/humanize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Humanize Route */
        post: operations["humanize_route_humanize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/style/fingerprint": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Style Fingerprint */
        post: operations["style_fingerprint_style_fingerprint_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/style/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Style Compare */
        post: operations["style_compare_style_compare_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/walkthrough": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Walkthrough Route */
        post: operations["walkthrough_route_walkthrough_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/personalize/spots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Personalize Spots */
        post: operations["personalize_spots_personalize_spots_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalyzeRequest */
        AnalyzeRequest: {
            /** Text */
            text: string;
            /** Target Grade */
            target_grade?: number | null;
        };
        /** AnalyzeResponse */
        AnalyzeResponse: {
            /** Score */
            score: number;
            subscores: components["schemas"]["Subscores"];
            /** Details */
            details: {
                [key: string]: {
                    [key: string]: components["schemas"]["MetricDetail"];
                };
            };
            /** Issues */
            issues: components["schemas"]["Issue"][];
            stats: components["schemas"]["Stats"];
            /** Sections */
            sections: components["schemas"]["Section"][];
            /** Protected */
            protected: components["schemas"]["ProtectedSpan"][];
            /** Languagetool */
            languagetool: boolean;
        };
        /** Change */
        Change: {
            /** Id */
            id: string;
            /** Orig Start */
            orig_start: number;
            /** Orig End */
            orig_end: number;
            /** New Start */
            new_start: number;
            /** New End */
            new_end: number;
            /** Original */
            original: string;
            /** Replacement */
            replacement: string;
            /** Transform */
            transform: string;
            /**
             * Category
             * @enum {string}
             */
            category: "clarity" | "rhythm" | "vocabulary" | "voice" | "grammar";
            /** Reason */
            reason: string;
            /** Confidence */
            confidence: number;
        };
        /** CompareRequest */
        CompareRequest: {
            /** Text */
            text: string;
            profile: components["schemas"]["StyleProfile"];
        };
        /** CompareResponse */
        CompareResponse: {
            /** Voice Match */
            voice_match: number;
            /** Differences */
            differences: components["schemas"]["StyleDifference"][];
        };
        /** ConceptEdge */
        ConceptEdge: {
            /** Source */
            source: string;
            /** Target */
            target: string;
            /** Label */
            label?: string | null;
            /** Weight */
            weight: number;
        };
        /** ConceptMapOut */
        ConceptMapOut: {
            /** Nodes */
            nodes: components["schemas"]["ConceptNode"][];
            /** Edges */
            edges: components["schemas"]["ConceptEdge"][];
        };
        /** ConceptNode */
        ConceptNode: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Weight */
            weight: number;
            /** Paragraphs */
            paragraphs: number[];
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /** FingerprintRequest */
        FingerprintRequest: {
            /** Samples */
            samples: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Spacy */
            spacy: string;
            /**
             * Lm
             * @enum {string}
             */
            lm: "kenlm" | "fallback";
            /** Lm Ready */
            lm_ready: boolean;
            /** Languagetool */
            languagetool: boolean;
        };
        /** HumanizeRequest */
        HumanizeRequest: {
            /** Text */
            text: string;
            /**
             * Tone
             * @default academic
             * @enum {string}
             */
            tone: "academic" | "neutral" | "casual";
            /**
             * Intensity
             * @default 3
             */
            intensity: number;
            /** Keep Terms */
            keep_terms?: string[];
            style_profile?: components["schemas"]["StyleProfile"] | null;
        };
        /** HumanizeResponse */
        HumanizeResponse: {
            /** Text */
            text: string;
            /** Changes */
            changes: components["schemas"]["Change"][];
            /** Protected */
            protected: components["schemas"]["ProtectedSpan"][];
            /** Score Before */
            score_before: number;
            /** Score After */
            score_after: number;
            /** Voice Match */
            voice_match?: number | null;
            /** Voice Match Before */
            voice_match_before?: number | null;
            stats: components["schemas"]["HumanizeStats"];
        };
        /** HumanizeStats */
        HumanizeStats: {
            /** Sentences */
            sentences: number;
            /** Sentences Considered */
            sentences_considered: number;
            /** Sentences Changed */
            sentences_changed: number;
            /** Candidates */
            candidates: number;
            /** Rejected */
            rejected: {
                [key: string]: number;
            };
            /** Languagetool */
            languagetool: boolean;
            /** Seconds */
            seconds: number;
        };
        /** Issue */
        Issue: {
            /** Start */
            start: number;
            /** End */
            end: number;
            /** Id */
            id: string;
            /** Category */
            category: string;
            /** Rule */
            rule: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "info" | "warn" | "error";
            /** Message */
            message: string;
            /** Suggestion */
            suggestion?: string | null;
            /** Lesson Slug */
            lesson_slug?: string | null;
        };
        /** KeyTerm */
        KeyTerm: {
            /** Term */
            term: string;
            /** Start */
            start: number;
            /** End */
            end: number;
            /** Definition */
            definition?: string | null;
            /** Source */
            source?: string | null;
        };
        /** MetricDetail */
        MetricDetail: {
            /** Value */
            value: number;
            /** Score */
            score: number;
        };
        /** ParagraphOut */
        ParagraphOut: {
            /** Index */
            index: number;
            /** Start */
            start: number;
            /** End */
            end: number;
            /** Section */
            section: string;
            /** Gist */
            gist: string;
            /** Key Terms */
            key_terms: components["schemas"]["KeyTerm"][];
            /** Simplified */
            simplified: string;
            /** Grade Before */
            grade_before: number;
            /** Grade After */
            grade_after: number;
        };
        /** ProtectedSpan */
        ProtectedSpan: {
            /** Start */
            start: number;
            /** End */
            end: number;
            /** Kind */
            kind: string;
            /** Text */
            text: string;
        };
        /** Section */
        Section: {
            /** Start */
            start: number;
            /** End */
            end: number;
            /** Name */
            name: string;
            /** Heading */
            heading: string;
        };
        /** SpotOut */
        SpotOut: {
            /** Id */
            id: string;
            /** Start */
            start: number;
            /** End */
            end: number;
            /** Insert At */
            insert_at: number;
            /** Pattern */
            pattern: string;
            /** Label */
            label: string;
            /** Prompt */
            prompt: string;
            /** Starter */
            starter: string;
            /** Quote */
            quote: string;
        };
        /** SpotsResponse */
        SpotsResponse: {
            /** Spots */
            spots: components["schemas"]["SpotOut"][];
        };
        /** Stats */
        Stats: {
            /** Words */
            words: number;
            /** Sentences */
            sentences: number;
            /** Sentence Lengths */
            sentence_lengths: number[];
            /** Fk Grade */
            fk_grade: number;
        };
        /** StyleDifference */
        StyleDifference: {
            /** Feature */
            feature: string;
            /** You */
            you: number;
            /** Text */
            text: number;
            /** Message */
            message: string;
        };
        /** StyleProfile */
        StyleProfile: {
            /** Features */
            features: {
                [key: string]: number;
            };
            /** Function Word Freqs */
            function_word_freqs: {
                [key: string]: number;
            };
            /** Sample Word Count */
            sample_word_count: number;
        };
        /** Subscores */
        Subscores: {
            /** Clarity */
            clarity: number | null;
            /** Rhythm */
            rhythm: number | null;
            /** Vocabulary */
            vocabulary: number | null;
            /** Voice */
            voice: number | null;
            /** Correctness */
            correctness: number | null;
        };
        /** TextRequest */
        TextRequest: {
            /** Text */
            text: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WalkthroughResponse */
        WalkthroughResponse: {
            /** Paragraphs */
            paragraphs: components["schemas"]["ParagraphOut"][];
            concept_map: components["schemas"]["ConceptMapOut"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    analyze_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyzeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyzeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    humanize_route_humanize_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HumanizeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HumanizeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    style_fingerprint_style_fingerprint_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FingerprintRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StyleProfile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    style_compare_style_compare_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompareRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompareResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    walkthrough_route_walkthrough_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TextRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WalkthroughResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    personalize_spots_personalize_spots_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TextRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpotsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
