/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze */
        post: operations["analyze_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/humanize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Humanize Route */
        post: operations["humanize_route_humanize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/style/fingerprint": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Style Fingerprint */
        post: operations["style_fingerprint_style_fingerprint_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/style/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Style Compare */
        post: operations["style_compare_style_compare_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/walkthrough": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Walkthrough Route */
        post: operations["walkthrough_route_walkthrough_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/personalize/spots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Personalize Spots */
        post: operations["personalize_spots_personalize_spots_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assess/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Assess Generate */
        post: operations["assess_generate_assess_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assess/grade": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Assess Grade */
        post: operations["assess_grade_assess_grade_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assess/viva/next": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Assess Viva Next */
        post: operations["assess_viva_next_assess_viva_next_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teachback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Teachback Route */
        post: operations["teachback_route_teachback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/doctor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Doctor */
        post: operations["doctor_doctor_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/extract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Files Extract */
        post: operations["files_extract_files_extract_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/export/docx": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Export Docx */
        post: operations["export_docx_export_docx_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/export/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Export Report */
        post: operations["export_report_export_report_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lessons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lessons */
        get: operations["lessons_lessons_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lessons/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lesson */
        get: operations["lesson_lessons__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalyzeRequest */
        AnalyzeRequest: {
            /** Text */
            text: string;
            /** Target Grade */
            target_grade?: number | null;
        };
        /** AnalyzeResponse */
        AnalyzeResponse: {
            /** Score */
            score: number;
            subscores: components["schemas"]["Subscores"];
            /** Details */
            details: {
                [key: string]: {
                    [key: string]: components["schemas"]["MetricDetail"];
                };
            };
            /** Issues */
            issues: components["schemas"]["Issue"][];
            stats: components["schemas"]["Stats"];
            /** Sections */
            sections: components["schemas"]["Section"][];
            /** Protected */
            protected: components["schemas"]["ProtectedSpan"][];
            /** Languagetool */
            languagetool: boolean;
        };
        /** AnswerIn */
        AnswerIn: {
            /** Id */
            id: string;
            /**
             * Answer
             * @default
             */
            answer: string;
        };
        /** Body_files_extract_files_extract_post */
        Body_files_extract_files_extract_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /** Change */
        Change: {
            /** Id */
            id: string;
            /** Orig Start */
            orig_start: number;
            /** Orig End */
            orig_end: number;
            /** New Start */
            new_start: number;
            /** New End */
            new_end: number;
            /** Original */
            original: string;
            /** Replacement */
            replacement: string;
            /** Transform */
            transform: string;
            /**
             * Category
             * @enum {string}
             */
            category: "clarity" | "rhythm" | "vocabulary" | "voice" | "grammar";
            /** Reason */
            reason: string;
            /** Confidence */
            confidence: number;
        };
        /** CompareRequest */
        CompareRequest: {
            /** Text */
            text: string;
            profile: components["schemas"]["StyleProfile"];
        };
        /** CompareResponse */
        CompareResponse: {
            /** Voice Match */
            voice_match: number;
            /** Differences */
            differences: components["schemas"]["StyleDifference"][];
        };
        /** ConceptEdge */
        ConceptEdge: {
            /** Source */
            source: string;
            /** Target */
            target: string;
            /** Label */
            label?: string | null;
            /** Weight */
            weight: number;
        };
        /** ConceptMapOut */
        ConceptMapOut: {
            /** Nodes */
            nodes: components["schemas"]["ConceptNode"][];
            /** Edges */
            edges: components["schemas"]["ConceptEdge"][];
        };
        /** ConceptNode */
        ConceptNode: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Weight */
            weight: number;
            /** Paragraphs */
            paragraphs: number[];
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /** ConceptSource */
        ConceptSource: {
            /** Concept */
            concept: string;
            span: components["schemas"]["Span"];
        };
        /** DoctorResponse */
        DoctorResponse: {
            /** Issues */
            issues: components["schemas"]["Issue"][];
            /** Counts */
            counts: {
                [key: string]: number;
            };
        };
        /** ExportDocxRequest */
        ExportDocxRequest: {
            /** Text */
            text: string;
            /**
             * Title
             * @default Untitled
             */
            title: string;
            /** Author */
            author?: string | null;
            understanding?: components["schemas"]["OwnershipNote"] | null;
        };
        /** ExtractResponse */
        ExtractResponse: {
            /** Text */
            text: string;
            /** Words */
            words: number;
            /**
             * Warnings
             * @default []
             */
            warnings: string[];
        };
        /** FingerprintRequest */
        FingerprintRequest: {
            /** Samples */
            samples: string[];
        };
        /** GateRow */
        GateRow: {
            /** Label */
            label: string;
            /** Value */
            value: number | null;
            /** Required */
            required: number;
            /** Passed */
            passed: boolean;
        };
        /** GenerateRequest */
        GenerateRequest: {
            /** Text */
            text: string;
            /**
             * Confusing Paragraphs
             * @default []
             */
            confusing_paragraphs: string[];
            /**
             * Seed
             * @default 0
             */
            seed: number;
        };
        /** GenerateResponse */
        GenerateResponse: {
            /** Questions */
            questions: components["schemas"]["QuestionOut"][];
        };
        /** GlossaryRow */
        GlossaryRow: {
            /** Term */
            term: string;
            /** Definition */
            definition?: string | null;
            /** Source */
            source?: string | null;
        };
        /** GradeRequest */
        GradeRequest: {
            /** Questions */
            questions: components["schemas"]["QuestionOut"][];
            /** Answers */
            answers: components["schemas"]["AnswerIn"][];
            /** Text */
            text?: string | null;
        };
        /** GradeResponse */
        GradeResponse: {
            /** Results */
            results: components["schemas"]["ResultOut"][];
            /** Total */
            total: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Spacy */
            spacy: string;
            /**
             * Lm
             * @enum {string}
             */
            lm: "kenlm" | "fallback";
            /** Lm Ready */
            lm_ready: boolean;
            /** Languagetool */
            languagetool: boolean;
        };
        /** HumanizeRequest */
        HumanizeRequest: {
            /** Text */
            text: string;
            /**
             * Tone
             * @default academic
             * @enum {string}
             */
            tone: "academic" | "neutral" | "casual";
            /**
             * Intensity
             * @default 3
             */
            intensity: number;
            /** Keep Terms */
            keep_terms?: string[];
            style_profile?: components["schemas"]["StyleProfile"] | null;
        };
        /** HumanizeResponse */
        HumanizeResponse: {
            /** Text */
            text: string;
            /** Changes */
            changes: components["schemas"]["Change"][];
            /** Protected */
            protected: components["schemas"]["ProtectedSpan"][];
            /** Score Before */
            score_before: number;
            /** Score After */
            score_after: number;
            /** Voice Match */
            voice_match?: number | null;
            /** Voice Match Before */
            voice_match_before?: number | null;
            stats: components["schemas"]["HumanizeStats"];
        };
        /** HumanizeStats */
        HumanizeStats: {
            /** Sentences */
            sentences: number;
            /** Sentences Considered */
            sentences_considered: number;
            /** Sentences Changed */
            sentences_changed: number;
            /** Candidates */
            candidates: number;
            /** Rejected */
            rejected: {
                [key: string]: number;
            };
            /** Languagetool */
            languagetool: boolean;
            /** Seconds */
            seconds: number;
        };
        /** Issue */
        Issue: {
            /** Start */
            start: number;
            /** End */
            end: number;
            /** Id */
            id: string;
            /** Category */
            category: string;
            /** Rule */
            rule: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "info" | "warn" | "error";
            /** Message */
            message: string;
            /** Suggestion */
            suggestion?: string | null;
            /** Lesson Slug */
            lesson_slug?: string | null;
        };
        /** KeyTerm */
        KeyTerm: {
            /** Term */
            term: string;
            /** Start */
            start: number;
            /** End */
            end: number;
            /** Definition */
            definition?: string | null;
            /** Source */
            source?: string | null;
        };
        /** LessonOut */
        LessonOut: {
            /** Slug */
            slug: string;
            /** Title */
            title: string;
            /** Summary */
            summary: string;
            /** Group */
            group: string;
            /** Markdown */
            markdown: string;
        };
        /** LessonSummary */
        LessonSummary: {
            /** Slug */
            slug: string;
            /** Title */
            title: string;
            /** Summary */
            summary: string;
            /** Group */
            group: string;
        };
        /** MetricDetail */
        MetricDetail: {
            /** Value */
            value: number;
            /** Score */
            score: number;
        };
        /** OwnershipNote */
        OwnershipNote: {
            /** Score */
            score: number;
            /** Student Share */
            student_share: number;
            /** Passed At */
            passed_at?: string | null;
        };
        /** OwnershipPartIn */
        OwnershipPartIn: {
            /** Label */
            label: string;
            /** Weight */
            weight: number;
            /** Value */
            value: number | null;
            /** Detail */
            detail: string;
        };
        /** ParagraphOut */
        ParagraphOut: {
            /** Index */
            index: number;
            /** Start */
            start: number;
            /** End */
            end: number;
            /** Section */
            section: string;
            /** Gist */
            gist: string;
            /** Key Terms */
            key_terms: components["schemas"]["KeyTerm"][];
            /** Simplified */
            simplified: string;
            /** Grade Before */
            grade_before: number;
            /** Grade After */
            grade_after: number;
        };
        /** ProtectedSpan */
        ProtectedSpan: {
            /** Start */
            start: number;
            /** End */
            end: number;
            /** Kind */
            kind: string;
            /** Text */
            text: string;
        };
        /** QuestionOut */
        QuestionOut: {
            /** Id */
            id: string;
            /**
             * Type
             * @enum {string}
             */
            type: "cloze" | "mcq" | "tf" | "viva";
            /** Prompt */
            prompt: string;
            /** Options */
            options?: string[] | null;
            /** Answer Key */
            answer_key: string;
            /**
             * Accepted
             * @default []
             */
            accepted: string[];
            source_span: components["schemas"]["Span"];
            /** Concepts */
            concepts: string[];
            /**
             * Explanation
             * @default
             */
            explanation: string;
            /** Level */
            level?: number | null;
            /** Difficulty */
            difficulty?: string | null;
            /** Kind */
            kind?: string | null;
        };
        /** QuizMiss */
        QuizMiss: {
            /** Prompt */
            prompt: string;
            /** Answer Key */
            answer_key: string;
            /**
             * Your Answer
             * @default
             */
            your_answer: string;
        };
        /** ResultOut */
        ResultOut: {
            /** Id */
            id: string;
            /** Correct */
            correct: boolean | null;
            /** Score */
            score: number;
            /** Feedback */
            feedback: string;
            /** Missed Concepts */
            missed_concepts: string[];
            /** Covered Concepts */
            covered_concepts: string[];
            source_span: components["schemas"]["Span"];
        };
        /** Section */
        Section: {
            /** Start */
            start: number;
            /** End */
            end: number;
            /** Name */
            name: string;
            /** Heading */
            heading: string;
        };
        /** Span */
        Span: {
            /** Start */
            start: number;
            /** End */
            end: number;
        };
        /** SpotOut */
        SpotOut: {
            /** Id */
            id: string;
            /** Start */
            start: number;
            /** End */
            end: number;
            /** Insert At */
            insert_at: number;
            /** Pattern */
            pattern: string;
            /** Label */
            label: string;
            /** Prompt */
            prompt: string;
            /** Starter */
            starter: string;
            /** Quote */
            quote: string;
        };
        /** SpotsResponse */
        SpotsResponse: {
            /** Spots */
            spots: components["schemas"]["SpotOut"][];
        };
        /** Stats */
        Stats: {
            /** Words */
            words: number;
            /** Sentences */
            sentences: number;
            /** Sentence Lengths */
            sentence_lengths: number[];
            /** Fk Grade */
            fk_grade: number;
        };
        /** StyleDifference */
        StyleDifference: {
            /** Feature */
            feature: string;
            /** You */
            you: number;
            /** Text */
            text: number;
            /** Message */
            message: string;
        };
        /** StyleProfile */
        StyleProfile: {
            /** Features */
            features: {
                [key: string]: number;
            };
            /** Function Word Freqs */
            function_word_freqs: {
                [key: string]: number;
            };
            /** Sample Word Count */
            sample_word_count: number;
        };
        /** Subscores */
        Subscores: {
            /** Clarity */
            clarity: number | null;
            /** Rhythm */
            rhythm: number | null;
            /** Vocabulary */
            vocabulary: number | null;
            /** Voice */
            voice: number | null;
            /** Correctness */
            correctness: number | null;
        };
        /** TeachbackRequest */
        TeachbackRequest: {
            /** Text */
            text: string;
            /** Explanation */
            explanation: string;
        };
        /** TeachbackResponse */
        TeachbackResponse: {
            /** Coverage */
            coverage: number;
            /** Covered */
            covered: string[];
            /** Missed */
            missed: string[];
            /** Similarity */
            similarity: number;
            /** Score */
            score: number;
            /** Feedback */
            feedback: string;
            /** Copied */
            copied: boolean;
            /** Missed Sources */
            missed_sources: components["schemas"]["ConceptSource"][];
        };
        /** TextRequest */
        TextRequest: {
            /** Text */
            text: string;
        };
        /** UnderstandingReportRequest */
        UnderstandingReportRequest: {
            /**
             * Title
             * @default Untitled
             */
            title: string;
            /** Author */
            author?: string | null;
            /** Date */
            date?: string | null;
            /**
             * Ownership Score
             * @default 0
             */
            ownership_score: number;
            /**
             * Student Share
             * @default 0
             */
            student_share: number;
            /**
             * Ownership Parts
             * @default []
             */
            ownership_parts: components["schemas"]["OwnershipPartIn"][];
            /**
             * Gate
             * @default []
             */
            gate: components["schemas"]["GateRow"][];
            /**
             * Gate Passed
             * @default false
             */
            gate_passed: boolean;
            /**
             * Mastered
             * @default []
             */
            mastered: string[];
            /**
             * Weak
             * @default []
             */
            weak: string[];
            /**
             * Glossary
             * @default []
             */
            glossary: components["schemas"]["GlossaryRow"][];
            /**
             * Viva
             * @default []
             */
            viva: components["schemas"]["VivaRow"][];
            /** Quiz Total */
            quiz_total?: number | null;
            /**
             * Quiz Missed
             * @default []
             */
            quiz_missed: components["schemas"]["QuizMiss"][];
            /** Teachback Coverage */
            teachback_coverage?: number | null;
            /** Teachback Explanation */
            teachback_explanation?: string | null;
            /**
             * Teachback Missed
             * @default []
             */
            teachback_missed: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VivaNextRequest */
        VivaNextRequest: {
            /** Text */
            text: string;
            /**
             * History
             * @default []
             */
            history: components["schemas"]["VivaTurnIn"][];
        };
        /** VivaNextResponse */
        VivaNextResponse: {
            /** Done */
            done: boolean;
            /** Index */
            index: number;
            /** Total */
            total: number;
            question?: components["schemas"]["QuestionOut"] | null;
            /** Difficulty */
            difficulty?: string | null;
            /**
             * Target Concepts
             * @default []
             */
            target_concepts: string[];
        };
        /** VivaRow */
        VivaRow: {
            /** Question */
            question: string;
            /**
             * Difficulty
             * @default
             */
            difficulty: string;
            /**
             * Answer
             * @default
             */
            answer: string;
            /**
             * Score
             * @default 0
             */
            score: number;
            /**
             * Feedback
             * @default
             */
            feedback: string;
            /**
             * Missed Concepts
             * @default []
             */
            missed_concepts: string[];
        };
        /** VivaTurnIn */
        VivaTurnIn: {
            /** Question */
            question: string;
            /**
             * Answer
             * @default
             */
            answer: string;
            /**
             * Score
             * @default 0
             */
            score: number;
            /** Id */
            id?: string | null;
            /** Missed Concepts */
            missed_concepts?: string[] | null;
        };
        /** WalkthroughResponse */
        WalkthroughResponse: {
            /** Paragraphs */
            paragraphs: components["schemas"]["ParagraphOut"][];
            concept_map: components["schemas"]["ConceptMapOut"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    analyze_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyzeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyzeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    humanize_route_humanize_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HumanizeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HumanizeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    style_fingerprint_style_fingerprint_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FingerprintRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StyleProfile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    style_compare_style_compare_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompareRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompareResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    walkthrough_route_walkthrough_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TextRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WalkthroughResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    personalize_spots_personalize_spots_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TextRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpotsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assess_generate_assess_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assess_grade_assess_grade_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GradeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GradeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assess_viva_next_assess_viva_next_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VivaNextRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VivaNextResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    teachback_route_teachback_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TeachbackRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeachbackResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    doctor_doctor_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TextRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DoctorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    files_extract_files_extract_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_files_extract_files_extract_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_docx_export_docx_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportDocxRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_report_export_report_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UnderstandingReportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lessons_lessons_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonSummary"][];
                };
            };
        };
    };
    lesson_lessons__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
